version: 2
jobs:
  build:

    macos:
      xcode: "9.2.0"

    steps:
      - checkout

      - run:
          name: Install ruby dependencies
          command: bundle install

      - run:
          name: Build and run tests
          command: sh build.sh /tmp/LayoutKit
